default_platform(:mac)

platform :mac do
  desc "Build the app in Debug configuration"
  lane :build_debug do
    build_mac_app(
      project: "./Xcompanion.xcodeproj",
      configuration: "Debug",
      skip_archive: true,
      scheme: "Xcompanion"
      silent: true,
    )
  end

  desc "Build and archive the app for Mac App Store distribution"
  lane :build_release do
    setup_ci if ENV['CI']

    personal_github_access_token = ENV["FASTLANE_MACH_REPO_GITHUB_ACCESS_TOKEN"]
    match(
      git_bearer_authorization:personal_github_access_token,
      type: 'appstore',
      readonly: true
    )

    sh("../tools/release/configure_xcodeproj_for_release_build.sh")
    build_mac_app(
      project: "./Xcompanion.xcodeproj",
      configuration: "Release",
      export_method: "mac-application",
      output_directory: "builds/release",
      output_name: "Xcompanion.app",
      scheme: "Xcompanion",
      silent: true,
      skip_archive: true
    )
    sh("../tools/release/cleanup_xcodeproj_after_release_build.sh")
  end
end
