// Copyright Xcompanion. All rights reserved.
// Licensed under the XXX License. See License.txt in the project root for license information.

Target.module(
  name: "App",
  dependencies: [
    .product(name: "Dependencies", package: "swift-dependencies"),
    .product(name: "KeyboardShortcuts", package: "KeyboardShortcuts"),
    "AccessibilityFoundation",
    "AccessibilityObjCFoundation",
    "AppEventService",
    "AppEventServiceInterface",
    "AskFollowUpTool",
    "Chat",
    "ChatAppEvents",
    "CheckpointService",
    "CheckpointServiceInterface",
    "DependencyFoundation",
    "DLS",
    "EditFilesTool",
    "ExecuteCommandTool",
    "ExtensionCommandHandler",
    "FileEditService",
    "FileEditServiceInterface",
    "FileSuggestionService",
    "FileSuggestionServiceInterface",
    "FoundationInterfaces",
    "LLMService",
    "LLMServiceInterface",
    "LoggingServiceInterface",
    "LSTool",
    "PermissionsService",
    "PermissionsServiceInterface",
    "ReadFileTool",
    "SearchFilesTool",
    "ServerService",
    "ServerServiceInterface",
    "SettingsFeature",
    "SettingsService",
    "SettingsServiceInterface",
    "ShellService",
    "ShellServiceInterface",
    "ThreadSafe",
    "ToolFoundation",
    "XcodeControllerService",
    "XcodeControllerServiceInterface",
    "XcodeObserverService",
    "XcodeObserverServiceInterface",
  ],
  resources: [],
  testDependencies: [])
