Target.module(
  name: "App",
  dependencies: [
    .product(name: "Dependencies", package: "swift-dependencies"),
    .product(name: "KeyboardShortcuts", package: "KeyboardShortcuts"),
    "AccessibilityFoundation",
    "AccessibilityObjCFoundation",
    "AppEventService",
    "AppEventServiceInterface",
    "AppUpdateService",
    "AppUpdateServiceInterface",
    "AskFollowUpTool",
    "BuildTool",
    "ChatAppEvents",
    "ChatFeature",
    "ChatHistoryService",
    "ChatHistoryServiceInterface",
    "CheckpointService",
    "CheckpointServiceInterface",
    "DependencyFoundation",
    "DLS",
    "EditFilesTool",
    "ExecuteCommandTool",
    "ExtensionCommandHandler",
    "FileSuggestionService",
    "FileSuggestionServiceInterface",
    "FoundationInterfaces",
    "HighlighterServiceInterface",
    "LLMService",
    "LLMServiceInterface",
    "LoggingService",
    "LoggingServiceInterface",
    "LSTool",
    "Onboarding",
    "PermissionsService",
    "PermissionsServiceInterface",
    "ReadFileTool",
    "SearchFilesTool",
    "ServerService",
    "ServerServiceInterface",
    "SettingsFeature",
    "SettingsService",
    "SettingsServiceInterface",
    "ShellService",
    "ShellServiceInterface",
    "ThreadSafe",
    "ToolFoundation",
    "XcodeControllerService",
    "XcodeControllerServiceInterface",
    "XcodeObserverService",
    "XcodeObserverServiceInterface",
  ],
  resources: [],
  testDependencies: [
    "AppEventServiceInterface",
    "ChatAppEvents",
    "ChatFoundation",
    "ConcurrencyFoundation",
    "FoundationInterfaces",
    "PermissionsServiceInterface",
    "SwiftTesting",
  ])
