#! /bin/bash

# Run a few quick pre-commit hooks to ensure the code is in a good state before committing.

# Fail on errors
set -euo pipefail

repo_root=$(git rev-parse --show-toplevel)
current_dir=$(pwd)

if [ -z "$repo_root" ]; then
    echo "Not a git repository"
    exit 1
fi

# Get current diff
current_diff=$(git diff HEAD)

cd "$repo_root"
./cmd.sh lint
./cmd.sh sync:dependencies

# Check for created changes
new_diff=$(git diff HEAD)

cd "$current_dir"

# If there are new changes, ask to re-commit
if [ "$new_diff" != "$current_diff" ]; then
    echo "Changes detected after running pre-commit hooks. Please review the changes."
    exit 1
else
    echo "No changes detected after running pre-commit hooks."
fi
