Target.module(
  name: "EditFilesTool",
  dependencies: [
"AppFoundation",
"CodePreview",
"ConcurrencyFoundation",
"DLS",
"FileDiffFoundation",
"FileDiffTypesFoundation",
"FoundationInterfaces",
"JSONFoundation",
"ServerServiceInterface",
"ThreadSafe",
"ToolFoundation",
"XcodeControllerServiceInterface",
],
  testDependencies: [
"AppFoundation",
"CodePreview",
"ConcurrencyFoundation",
"FileDiffFoundation",
"FoundationInterfaces",
"JSONFoundation",
"SwiftTesting",
"ToolFoundation",
"XcodeControllerServiceInterface",
])
