Target.module(
  name: "SettingsFeature",
  dependencies: [
    "AppFoundation",
    "AppUpdateServiceInterface",
    "ChatFoundation",
    "ConcurrencyFoundation",
    "DLS",
    "ExtensionEventsInterface",
    "FoundationInterfaces",
    "LLMFoundation",
    "LocalServerServiceInterface",
    "LoggingServiceInterface",
    "SettingsServiceInterface",
    "SharedValuesFoundation",
    "ShellServiceInterface",
    "ToolFoundation",
    "XcodeControllerServiceInterface",
    "XcodeObserverServiceInterface",
  ],
  testDependencies: [
    "FoundationInterfaces",
    "LLMFoundation",
    "SettingsServiceInterface",
    "SwiftTesting",
  ])
