Target.module(
  name: "XcodeControllerService",
  dependencies: [
    .product(name: "XCLogParser", package: "XCLogParser"),
    "AppEventServiceInterface",
    "AppFoundation",
    "ConcurrencyFoundation",
    "DependencyFoundation",
    "ExtensionEventsInterface",
    "FileDiffFoundation",
    "FoundationInterfaces",
    "LoggingServiceInterface",
    "SettingsServiceInterface",
    "SharedValuesFoundation",
    "ShellServiceInterface",
    "ThreadSafe",
    "XcodeControllerServiceInterface",
    "XcodeObserverServiceInterface",
  ],
  testDependencies: [
    "AppEventServiceInterface",
    "AppFoundation",
    "ExtensionEventsInterface",
    "FileDiffFoundation",
    "FoundationInterfaces",
    "SettingsServiceInterface",
    "SharedValuesFoundation",
    "ShellServiceInterface",
    "SwiftTesting",
    "XcodeControllerServiceInterface",
    "XcodeObserverServiceInterface",
  ])
