Target.module(
  name: "ChatFeature",
  dependencies: [
    .product(name: "Dependencies", package: "swift-dependencies"),
    .product(name: "Down", package: "Down"),
    .product(name: "HighlightSwift", package: "highlightswift"),
    "AppEventServiceInterface",
    "AppFoundation",
    "AppUpdateServiceInterface",
    "ChatAppEvents",
    "ChatCompletionServiceInterface",
    "ChatFeatureInterface",
    "ChatFoundation",
    "ChatServiceInterface",
    "CheckpointServiceInterface",
    "CodePreview",
    "ConcurrencyFoundation",
    "DLS",
    "ExtensionEventsInterface",
    "FileDiffFoundation",
    "FileDiffTypesFoundation",
    "FileSuggestionServiceInterface",
    "FoundationInterfaces",
    "HighlighterServiceInterface",
    "JSONFoundation",
    "LLMFoundation",
    "LLMServiceInterface",
    "LocalServerServiceInterface",
    "LoggingServiceInterface",
    "SettingsServiceInterface",
    "SharedValuesFoundation",
    "ShellServiceInterface",
    "ThreadSafe",
    "ToolFoundation",
    "XcodeObserverServiceInterface",
  ],
  resources: [.process("Resources")],
  testDependencies: [
    "AccessibilityFoundation",
    "AppEventServiceInterface",
    "ChatAppEvents",
    "ChatFeatureInterface",
    "ChatFoundation",
    "ChatServiceInterface",
    "CheckpointServiceInterface",
    "ConcurrencyFoundation",
    "FileSuggestionServiceInterface",
    "FoundationInterfaces",
    "LLMFoundation",
    "LLMServiceInterface",
    "LocalServerServiceInterface",
    "SettingsServiceInterface",
    "SwiftTesting",
    "XcodeObserverServiceInterface",
  ])
