Target.module(
  name: "LLMService",
  dependencies: [
    .product(name: "JSONScanner", package: "JSONScanner"),
    "AppFoundation",
    "ChatFoundation",
    "ConcurrencyFoundation",
    "DependencyFoundation",
    "JSONFoundation",
    "LLMFoundation",
    "LLMServiceInterface",
    "LoggingServiceInterface",
    "ServerServiceInterface",
    "SettingsServiceInterface",
    "ThreadSafe",
    "ToolFoundation",
  ],
  testDependencies: [
    "AppFoundation",
    "ConcurrencyFoundation",
    "JSONFoundation",
    "LLMFoundation",
    "LLMServiceInterface",
    "ServerServiceInterface",
    "SettingsServiceInterface",
    "SwiftTesting",
    "ThreadSafe",
    "ToolFoundation",
  ])
