# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: MacOS App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  release:
    runs-on: macos-latest
    steps:
    - uses: swift-actions/setup-swift@v2
      with:
        swift-version: "6.1"
    - name: Get swift version
      run: swift --version
    - uses: actions/setup-node@v4
      with:
        node-version-file: "./local-server/.nvmrc"
    - name: Get node version
      run: node --version
    - name: Install node dependencies
      run: cd local-server && yarn install
    - uses: actions/checkout@v4
    - name: Make release
      run: cd app && make release

  test:
    runs-on: macos-latest
    steps:
    - uses: swift-actions/setup-swift@v2
      with:
        swift-version: "6.1"
    - name: Get swift version
      run: swift --version
    - uses: actions/checkout@v4
    - name: Run tests
      run: cd app && make clean && make test

  lint:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@master
    - name: Install swiftformat
      run: brew install swiftformat
    - name: Run linter
      run: cd app && make lint
    - name: Verify that `make lint` did not change outputs (if it did, please re-run it and re-commit!)
      run: git diff --exit-code

  sync-dependencies:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run sync dependencies
      run: cd app && make sync-dependencies
    - name: Verify that `make sync-dependencies` did not change outputs (if it did, please re-run it and re-commit!)
      run: git diff --exit-code
