# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Local Server

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version-file: "./local-server/.nvmrc"
    - name: Get node version
      run: node --version
    - name: Install dependencies
      run: cd local-server && yarn install
    - name: Run tests
      run: cd local-server && yarn test

  tsc:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version-file: "./local-server/.nvmrc"
    - name: Get node version
      run: node --version
    - name: Install dependencies
      run: cd local-server && yarn install
    - name: Run tests
      run: cd local-server && yarn tsc

  tsc:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version-file: "./local-server/.nvmrc"
    - name: Get node version
      run: node --version
    - name: Install dependencies
      run: cd local-server && yarn install
    - name: Run tests
      run: cd local-server && yarn lint:fix
    - name: Verify that `make lint` did not change outputs (if it did, please re-run it and re-commit!)
      run: git diff --exit-code
