name: Integration tests

on:
  push:
    branches: [ "main" ]
concurrency:
  group: main-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}
jobs:
  warm-up-release-app-cache:
    runs-on: macos-26
    timeout-minutes: 60
    steps:
    - name: MacOS version
      run: sw_vers
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version-file: "./local-server/.nvmrc"
    - uses: gsabran/setup-swift@main
      with:
        swift-version: "6.2"
        soft-fail-version-check: true
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '26.0'
    - name: Load npm cache
      uses: actions/cache@v4
      with:
        path: local-server/node_modules
        key: ${{ runner.os }}-npm-modules-${{ hashFiles('local-server/yarn.lock') }}
    - name: Install node dependencies
      run: cd local-server && yarn install && yarn build && yarn copy-to-app
    # See https://github.com/actions/runner-images/issues/10722#issuecomment-2387952421
    - uses: extractions/netrc@v1
      with:
        machine: github.com
        username: oauth2
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Install fastlane dependencies
      run: |
        cd app/fastlane && gem install bundler && bundle install
    - name: Make release
      run: cd app/fastlane && bundle exec fastlane mac build_release
      env:
        FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: 60
        FASTLANE_XCODEBUILD_SETTINGS_RETRIES: 10
        MATCH_PASSWORD: ${{ secrets.FASTLANE_MACH_PASSWORD }}
        FASTLANE_MACH_REPO_GITHUB_ACCESS_TOKEN: ${{ secrets.FASTLANE_MACH_REPO_GITHUB_ACCESS_TOKEN }}
        GITHUB_RUN_ATTEMPT: ${{ github.run_attempt }}
    - name: Cache derived data
      uses: actions/cache/save@v4
      with:
        path: app/build/derived_data
        key: ${{ runner.os }}-app-derived-data-main
